// Public entrypoint for `@agent-ctrl/client`.

export { AgentCtrl, type AgentCtrlOptions, type OpenedSession } from "./client.js";
export { PROTOCOL_VERSION, systemTimeToMs } from "./types.js";
export type {
  Action,
  ActionResult,
  AppContext,
  BatchStep,
  BatchStepOutcome,
  Bounds,
  ClipboardOp,
  FindMatch,
  FindQuery,
  GetField,
  GetResult,
  IsResult,
  MouseButton,
  MouseOp,
  Node,
  NodeState,
  ObservedMatch,
  RefEntry,
  RefId,
  RefMap,
  Region,
  Request,
  RequestOp,
  Response,
  Role,
  RustSystemTime,
  ScreenshotTarget,
  SessionId,
  Snapshot,
  SnapshotOptions,
  StateField,
  SurfaceKind,
  WaitOptions,
  WaitOutcome,
  WaitPredicate,
  WindowContext,
  WindowInfo,
  WindowTarget,
} from "./types.js";
